name: cd

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: prod
    env:
      CDF_CLIENT_NAME: ${{ secrets.CDF_CLIENT_NAME }}
      CDF_CLUSTER: ${{ secrets.CDF_CLUSTER }}
      CDF_DATA_MODEL_EXTERNAL_ID: ${{ secrets.CDF_DATA_MODEL_EXTERNAL_ID }}
      CDF_DATA_MODEL_SPACE: ${{ secrets.CDF_DATA_MODEL_SPACE }}
      CDF_DATA_MODEL_VERSION: ${{ secrets.CDF_DATA_MODEL_VERSION }}
      CDF_CLIENT_ID: ${{ secrets.CDF_CLIENT_ID }}
      CDF_CLIENT_SECRET: ${{ secrets.CDF_CLIENT_SECRET }}
      CDF_TOKEN_URL: ${{ secrets.CDF_TOKEN_URL }}
      CDF_PROJECT: ${{ secrets.CDF_PROJECT }}

    steps:
      - uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Sync deps
        run: uv sync --locked --all-extras --dev

      - name: Build + Test
        run: source ./scripts/test.sh

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
